### ISSUE TITLE
Cập Nhật Data

### ISSUE THREAD

**Issue by nguyenphuc22** [nguyenphuc22/AppDataVisualization#10]
Mục tiêu: Ứng dụng sẽ tiến hành cập nhật data của người dùng cung cấp vào database ( excel ). Ứng dụng sẽ lấy data đó đi phân tích như kịch bản các bạn khác viết.

Đầu vào: Người dùng cung cấp các loại file csv, excel. Người dùng có thể upload một hay nhiều file 1 lúc.

Đầu ra: Ứng dụng sẽ ghị data vào database tương ứng. Nếu là data được cung cấp là product thì ghi  vào file product, nếu là file review sẽ ghi vào file review. Ứng dụng sẽ tự động cập nhật data mới lên các giả thuyết.

Chức năng dược dùng ở màn hình nào: Chức này được dùng ở các trang nào thuộc review hoặc product ( Nếu là trang giả thuyết thuộc một trong 2 tag review hoặc product cũng hiện chức năng này).

Ngoại lệ:
- Nếu người dùng upload file không phải csv hoặc excel, thông báo file không hợp lệ.
- Nếu người dùng upload file không đúng với cấu trúc product hoặc review, thông báo file không đúng cấu trúc.
- Nếu người dùng đang ở pages về product mà upload file cấu trúc review, thông báo file không đúng cấu trúc.

**Comment by BinhPQ2** [comment]
@nguyenphuc22 Câu hỏi:

1. Tại sao cho người dùng quyền upload nhiều file để làm gì? Giới hạn cho họ upload 1 file thôi.
2. Cần làm rõ về cấu trúc file, thế nào gọi là 1 file product, 1 file review? Liệu có phải đủ hết các Columns mới tính là hợp lệ không?

**Comment by nguyenphuc22** [comment]
@BinhPQ2 
1. Cũng được nhé. Nhớ thêm action cho nếu họ upload thêm nữa sẽ làm gì ?
2. Hiện tại làm đơn giản. đủ hết cột mới xem là hợp lệ. Sau khi app chạy được sẽ tính thêm
Được không Bình ?

**Comment by BinhPQ2** [comment]
@nguyenphuc22 
1. Thêm action là sao t không hiểu? T nghĩ nếu upload và xử lý thành công thì sẽ nhảy ra chữ nói "Bạn đã upload thành công file Product/Review" thôi.
2. Ok.

**Comment by nguyenphuc22** [comment]
1. Người dùng kéo thả 2 file vào một lúc thì seo, UI hiện tại cho phép người upload một lúc 2 files đó. Nên khi làm chỉ một file thì sữa UI lại. Sữa sao cảm thấy hợp lý không bug là được

**Comment by BinhPQ2** [comment]
1. Ok

**Comment by BinhPQ2** [comment]
1. Switching from Review page to Product page will replace the review file with product file for some reason.
